package com.mamy.android.ui.theme

import androidx.compose.ui.graphics.Color

// Light scheme (warm sand + emerald accent for "listening")
val LightPrimary = Color(0xFF2E7D5C)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFB6F1D8)
val LightOnPrimaryContainer = Color(0xFF002115)
val LightSecondary = Color(0xFF4D6358)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD0E8DA)
val LightOnSecondaryContainer = Color(0xFF0A1F17)
val LightTertiary = Color(0xFFB75A1C)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightBackground = Color(0xFFF7F4EE)
val LightOnBackground = Color(0xFF1A1C1A)
val LightSurface = Color(0xFFFFFBF5)
val LightOnSurface = Color(0xFF1A1C1A)
val LightError = Color(0xFFB3261E)
val LightOnError = Color(0xFFFFFFFF)

// Dark scheme
val DarkPrimary = Color(0xFF9BD5BC)
val DarkOnPrimary = Color(0xFF003828)
val DarkPrimaryContainer = Color(0xFF105D43)
val DarkOnPrimaryContainer = Color(0xFFB6F1D8)
val DarkSecondary = Color(0xFFB4CCBE)
val DarkOnSecondary = Color(0xFF20352B)
val DarkSecondaryContainer = Color(0xFF364C41)
val DarkOnSecondaryContainer = Color(0xFFD0E8DA)
val DarkTertiary = Color(0xFFFFB68A)
val DarkOnTertiary = Color(0xFF552100)
val DarkBackground = Color(0xFF101412)
val DarkOnBackground = Color(0xFFE2E3DE)
val DarkSurface = Color(0xFF181B19)
val DarkOnSurface = Color(0xFFE2E3DE)
val DarkError = Color(0xFFF2B8B5)
val DarkOnError = Color(0xFF601410)
